### ISSUE TITLE
raise when the user passes in collections not part of the typing machinery

### ISSUE THREAD

**Issue by usatosi** [bloomberg/attrs-strict#21]
**Describe the bug**
When I set a dict value to the argument defined as type=dict, AttributeError was risen.

**To Reproduce**
```python
import attr
from attrs_strict import type_validator

@attr.s
class A:
    b = attr.ib(type=dict,validator=type_validator())

A(b={"abc":1})
```

This code results in the following error.

```shell
AttributeError                            Traceback (most recent call last)
<ipython-input-38-eca5783af58d> in <module>
----> 1 A(b={"abc":1})

<attrs generated init __main__.A-5> in __init__(self, b)
      2     self.b = b
      3     if _config._run_validators is True:
----> 4         __attr_validator_b(self, __attr_b, self.b)

/usr/lib/python3.7/site-packages/attrs_strict/_type_validation.py in _validator(instance, attribute, field)

/usr/lib/python3.7/site-packages/attrs_strict/_type_validation.py in _validate_elements(attribute, value, expected_type)

/usr/lib/python3.7/site-packages/attrs_strict/_type_validation.py in _handle_dict(attribute, container, expected_type)

AttributeError: type object 'dict' has no attribute '__args__'
```

**Expected behavior**

Error should not be occurred.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Operating System and Version: [e.g. Arch Linux(kernel:5.3.7.arch1-1]
 - Python: 3.7.4
 - Browser [e.g. Firefox, Safari] (if applicable): N/A

Is there any my misunderstandings?

**Comment by gaborbernat** [comment]
@usatosi the type information must be pass as PEP-484 defines it here https://www.python.org/dev/peps/pep-0484/, see here for CPython implementation https://docs.python.org/3/library/typing.html . For dictionaries this would be via https://docs.python.org/3/library/typing.html#typing.Dict. Supporting ``list``, ``dict`` is in discussion at language level, but that's unlikely to be a thing before 3.9 version of cpython.


That being said we should give here a more helpful message, something along the lines that collection types must be part of the typing module.

**Comment by erikseulean** [comment]
I think we could also specify in the documentation that the library is expecting pep484 type hints, however I want to double checked that if you specify a type as `Dict` without types for key and values it doesn't give you that error.

**Comment by erikseulean** [comment]
I had a look into this. When the type is not specified for the `key` or `value` of the dictionary, they are being defaulted to `TypeVar(name="KT")` and `TypeVar(name="VT")`. These cases are not handled since the library does not have support for generics yet. 

There is somebody that worked on adding that but they still wait for permission to contribute to the project.

**Comment by usatosi** [comment]
@gaborbernat 
Thank you for your comment. Changing type definition to `Dict[str, str]`, AttributeError disappeared and I got it on runtime as expected.

## code

```python
import attr
from attrs_strict import type_validator
from typing import Dict

@attr.s
class A:
    b = attr.ib(type=Dict[str, str],validator=type_validator())

A(b={"abc":1})
```
## result

```
AttributeTypeError                        Traceback (most recent call last)
<ipython-input-45-eca5783af58d> in <module>
----> 1 A(b={"abc":1})

<attrs generated init __main__.A-7> in __init__(self, b)
      2     self.b = b
      3     if _config._run_validators is True:
----> 4         __attr_validator_b(self, __attr_b, self.b)

/usr/lib/python3.7/site-packages/attrs_strict/_type_validation.py in _validator(instance, attribute, field)

/usr/lib/python3.7/site-packages/attrs_strict/_type_validation.py in _validate_elements(attribute, value, expected_type)

/usr/lib/python3.7/site-packages/attrs_strict/_type_validation.py in _handle_dict(attribute, container, expected_type)

/usr/lib/python3.7/site-packages/attrs_strict/_type_validation.py in _handle_dict(attribute, container, expected_type)

/usr/lib/python3.7/site-packages/attrs_strict/_type_validation.py in _validate_elements(attribute, value, expected_type)

AttributeTypeError: b must be typing.Dict[str, str] (got 1 that is a <class 'int'>) in {'abc': 1}
```

@erikseulean 

Yes, I hope the document refers to PEP484.

Thank you all. Let me close this issue.
