### ISSUE TITLE
Annotate and make attrs-strict PEP 561 compatible

### ISSUE THREAD

**Issue by keiclone** [bloomberg/attrs-strict#24]
**Is your feature request related to a problem? Please describe.**
`attrs-strict` is great because it adds runtime type validation to my attrs classes, but it'd be great if it could play nice with my static type checkers as well.

**Describe the solution you'd like**
Annotate all the functions and add `py.typed` to `setup.py` per [PEP 561](https://www.python.org/dev/peps/pep-0561/)

**Describe alternatives you've considered**
A quick way to incorporate `attrs-strict` in my projects would be to add some stubs for it to `MYPYPATH`. Might as well contribute the effort back.

**Comment by erikseulean** [comment]
This looks like a good idea; if you'd like to implement it yourself @keiclone I can assign this to you.

**Comment by keiclone** [comment]
Sure thing, I can take this.

**Comment by erikseulean** [comment]
Great, I assigned this to you.

**Comment by erikseulean** [comment]
@keiclone any updates on this ?

**Comment by keiclone** [comment]
Sorry for the delay, I should be able to find some time after the holidays.

**Comment by keiclone** [comment]
working on this right now. looking at the README and `tox.ini`, it seems up to this point, we have been supporting python 2.7. Note that afaik, there's no way to proceed with this without breaking backwards compatibility with 2.7, since the types will affect function signatures.

Since the current year is now 2020 and [python 2.7 is officially deprecated](https://pythonclock.org/), are we okay with dropping support for it now?

**Comment by gaborbernat** [comment]
> Since the current year is now 2020 and python 2.7 is officially deprecated

CPython 2.7 might be no longer maintained, but PyPy 2.7 is still supported. So the real question is do we want to drop that platform? I'm not 100% sure on that.

**Comment by alexchamberlain** [comment]
Personally, for a library like this, I'd vote against removing 2.7 support unless absolutely necessary or because the upstream package (attrs) removes it.

**Comment by erikseulean** [comment]
I'd prefer to keep the 2.7 support longer, that being said I'd say this should be parked until we drop the 2.7 support ?

**Comment by erikseulean** [comment]
Done!
