### ISSUE TITLE
Support for Tuple is incorrect/incomplete

### ISSUE THREAD

**Issue by douardda** [bloomberg/attrs-strict#37]
When declaring an attribute as a Tuple, there are 2 possible forms:

Simple form, like `Tuple[str]` or `Tuple[int, int]`, should be used for fixed size tuple declarations, which seems to be what attrs-strict currently supports. But there is also the form with an ellipsis to declare a  variable-length tuple of homogeneous type (see https://docs.python.org/3.7/library/typing.html#typing.Tuple )

It seems to me that this should at the very least be mentioned in the documentation (in the "What is currently supported ?" section), or be fixed to have proper support for this pattern.

eg.

```
@attr.s()
class Model:
    item = attr.ib(type=Tuple[int, ...], validator=type_validator())

obj = Model(item=(1, 2, 3))
```

will raise:
```
TupleError: Element (1, 2, 3) has more elements than types specified in typing.Tuple[int, ...]. Expected 2 received 3
```

**Comment by erikseulean** [comment]
I think this is a bug, and as you mentioned, we should either fix it or add it to the documentation.
