### ISSUE TITLE
Python 2.7 install_requires missing package

### ISSUE THREAD

**Issue by lironhl** [bloomberg/attrs-strict#49]
**Describe the bug**
Even though `attrs-strict` uses `funcsigs` package in [_type_validation.py](https://github.com/bloomberg/attrs-strict/blob/23dd822037e9afe4a58493b1fb3702431804ed09/src/attrs_strict/_type_validation.py#L23) it's not specified inside [setup.cfg](https://github.com/bloomberg/attrs-strict/blob/23dd822037e9afe4a58493b1fb3702431804ed09/setup.cfg) `install_requires`.

**To Reproduce**
Just import the package in Python 2.7
`import attrs_strict`

**Comment by erikseulean** [comment]
This is done! Thank you @lironhl !

**Comment by gaborbernat** [comment]
https://pypi.org/project/attrs-strict/0.1.2/
