### ISSUE TITLE
Assign validators for a whole class

### ISSUE THREAD

**Issue by max-arnold** [bloomberg/attrs-strict#83]
Assigning validators to each field is too verbose and repetitive `attrs.field(validator=type_validator())`.

Is there a way to validate a whole class?

```
@attrs.define
class MyClass:
    id: str
    attr1: int
    attr2: str
    fields: Dict[str, Any] = attrs.field(default={})

myc = MyClass('123', 1, '345')
attrs_strict.validate(myc)
```

Or maybe through a class decorator?

**Comment by gaborbernat** [comment]
There isn't, and we don't plan to provide within this library itself for now.

**Comment by erikseulean** [comment]
As a class decorator, I don't think it's doable, unless it's being done in attrs directly. 

Second is doable but arguably not very elegant.
